### ISSUE TITLE
Bower instructions in README are incorrect

### ISSUE THREAD

**Issue by dotherightthing** [jasny/bootstrap#257]
To replicate:

```
// bower.json
{
    "name": "name",
    "version": "1.0.0",
    "main": "README.md",
    "license": "All rights reserved",
    "private": true,
    "ignore": [
        "**/.*",
        "node_modules",
        "bower_components",
        "test",
        "tests"
    ],
    "dependencies": {
        "bootstrap": "https://github.com/jasny/bootstrap.git#v3.1.3"
    }
}

// Terminal
bower cache clean
bower install
```

The initial installation works fine, however running `bower install` a second time fails with this error:

```
bower error         Maximum call stack size exceeded

Stack trace:
N/A

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:72:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:111:22)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/install.js:35:16
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.5
Node version: 0.10.22
OS: Darwin 13.1.0 x64
```

Thanks,
Dan

**Comment by Minstel** [comment]
Bower instructions seem like correct now.  Closing.
